### PR TITLE
bugfix: waiting containers block pod termination

### LINKED ISSUE #406: Statefulset's pod got stuck in terminating forever after deleting
Bug Report
---

Type: *bug report*

### What happened

Statefulset's pod got stuck in terminating forever after deleting, and container state in the pod status shows as following

```
containerStatuses:
  image: ""
  lastState:
      terminated:
        exitCode: 137
        finishedAt: null
        message: The container could not be located when the pod was deleted.  The
          container used to be Running
        reason: ContainerStatusUnknown
        startedAt: null
  name: xxx-container
  ready: false
  restartCount: 0
  started: false
  state:
    waiting:
      reason: ContainerCreating
```

### What you expected to happen

Pod can be deleted.

### Environment
- hybridnet version: v0.8.7
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Kubernetes version:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by hhyasdf**
Pull Request Description
---

### Describe what this PR does / why we need it
As mentioned in #406, now sts pods might get stuck in "Terminating" because of unknow _waiting_ container state. To check if pod is completely terminated, we should check if "all the containers' state are not _running_" rather than "all the containers‘ state are _terminated_".

### Does this pull request fix one issue?

Fixes #406 

### Special notes for reviews

### CODE REVIEW

File: pkg/controllers/utils/pod.go [hunk 1]
```diff
@@ -52,8 +52,9 @@ func PodIsScheduled(pod *v1.Pod) bool {
 }
 
 func PodIsTerminated(pod *v1.Pod) bool {
```
Comment (sjtufl) [inline pkg/controllers/utils/pod.go:54]: What about changing func name to something like `PodHasNoRunningContainer`?

**Review by sjtufl — APPROVED** [review]
/lgtm

File: pkg/controllers/utils/pod.go (hunk 1 above)
Comment (hhyasdf) [reply pkg/controllers/utils/pod.go]: done~

**Review by mars1024 — APPROVED** [review]
/lgtm
